export type VetDrug = { category:string; name:string; aliases:string[]; species:string[]; doseMgKg:[number,number]; fixedDose?:string; route:string; frequency:string; cautions:string[]; diagnoses:string[]; systems:string[]; source:string };
const cd=["cat","dog"], all=["cat","dog","rabbit","hamster","bird"];
const COMMON={cautions:["كلوي","renal","kidney","كبد","hepatic","جفاف","dehydrat","حامل","pregnan"],source:"MSD Veterinary Manual"};
export const VET_DRUGS:VetDrug[]=[
 {category:"مضاد حيوي",name:"Amoxicillin/Clavulanate / أموكسيسيلين كلافولانات",aliases:["amoxiclav","augmentin","اموكس","أوغمنتين"],species:cd,doseMgKg:[12.5,25],route:"PO",frequency:"كل 12 ساعة",...COMMON,diagnoses:["التهاب بكتيري","التهاب جلد","التهاب تنفسي","التهاب بولي","التهاب فم","خراج فموي"],systems:["respiratory","digestive","urinary","integumentary","oral"]},
 {category:"مضاد حيوي",name:"Ampicillin / أمبيسيلين",aliases:["ampicillin","امبيسيلين"],species:cd,doseMgKg:[10,40],route:"IV / IM / SC",frequency:"كل 6–12 ساعة",...COMMON,diagnoses:["التهاب بكتيري","إنتان"],systems:["respiratory","digestive","urinary"]},
 {category:"مضاد حيوي",name:"Ceftriaxone / سيفترياكسون",aliases:["ceftriaxone","سيفترياكسون","سفيتراكزون"],species:cd,doseMgKg:[25,50],route:"IM / IV",frequency:"حسب البروتوكول",...COMMON,diagnoses:["التهاب بكتيري","إنتان"],systems:["respiratory","urinary","digestive"]},
 {category:"مضاد حيوي",name:"Cephalexin / سيفالكسين",aliases:["cephalexin","سيفالكسين"],species:cd,doseMgKg:[15,30],route:"PO",frequency:"كل 8–12 ساعة",...COMMON,diagnoses:["التهاب جلد","التهاب بكتيري","التهاب فم"],systems:["integumentary","oral"]},
 {category:"مضاد حيوي",name:"Clindamycin / كليندامايسين",aliases:["clindamycin","كليندامايسين"],species:cd,doseMgKg:[5,12.5],route:"PO",frequency:"كل 12 ساعة",cautions:["كبد","hepatic","مريء","esoph"],diagnoses:["التهاب أسنان","التهاب فم","عظم","توكسوبلازما"],systems:["oral","musculoskeletal"],source:"MSD Veterinary Manual - Macrolides"},
 {category:"مضاد حيوي",name:"Doxycycline / دوكسيسيكلين",aliases:["doxy","doxycycline","دوكسي","دوكسيسيكلين"],species:["cat","dog","bird","hamster"],doseMgKg:[5,10],route:"PO",frequency:"كل 12–24 ساعة",cautions:["حامل","pregnan","مريء","esoph","كبد","hepatic"],diagnoses:["التهاب تنفسي","كلاميديا","مايكوبلازما","قراد"],systems:["respiratory","blood"],source:"MSD Veterinary Manual - Tetracyclines"},
 {category:"مضاد حيوي",name:"Azithromycin / أزيثرومايسين",aliases:["azithromycin","zithromax","ازيثرو"],species:["cat","dog","bird"],doseMgKg:[5,15],route:"PO",frequency:"كل 24 ساعة",...COMMON,diagnoses:["التهاب تنفسي","كلاميديا"],systems:["respiratory"],source:"MSD Veterinary Manual - Macrolides"},
 {category:"مضاد حيوي",name:"Enrofloxacin / إنروفلوكساسين",aliases:["enrofloxacin","baytril","إنروفلوكساسين","بايتريل"],species:["dog","bird","rabbit","hamster"],doseMgKg:[5,20],route:"PO / IM / SC",frequency:"كل 12–24 ساعة حسب النوع",cautions:["كلوي","renal","جفاف","dehydrat","صغير","growth","شبكية","retina"],diagnoses:["التهاب تنفسي","التهاب بولي","التهاب بكتيري"],systems:["respiratory","urinary","digestive"],source:"MSD Veterinary Manual - Fluoroquinolones"},
 {category:"مضاد حيوي/طفيليات",name:"Metronidazole / مترونيدازول",aliases:["metronidazole","flagyl","مترونيدازول","فلاجيل"],species:all,doseMgKg:[10,25],route:"PO / IV",frequency:"كل 12–24 ساعة",cautions:["كبد","hepatic","عصبي","neurolog","حامل","pregnan"],diagnoses:["التهاب أمعاء","إسهال","جيارديا","لاهوائيات"],systems:["digestive"],source:"MSD Veterinary Manual - Nitroimidazoles"},
 {category:"مضاد حيوي",name:"Trimethoprim-Sulfa / ترايميثوبريم سلفا",aliases:["trimethoprim","sulfa","tmp-smx","سلفا"],species:cd,doseMgKg:[15,30],route:"PO",frequency:"كل 12–24 ساعة",...COMMON,diagnoses:["التهاب بولي","التهاب تنفسي","كوكسيديا"],systems:["urinary","respiratory","digestive"],source:"MSD Veterinary Manual - Potentiated Sulfonamides"},
 {category:"مضاد حيوي",name:"Gentamicin / جنتامايسين",aliases:["gentamicin","جنتامايسين"],species:cd,doseMgKg:[5,14],route:"IV / IM / SC",frequency:"كل 24 ساعة",cautions:["كلوي","renal","kidney","جفاف","dehydrat","سمع","hearing"],diagnoses:["إنتان","التهاب بكتيري شديد"],systems:["urinary","respiratory"],source:"MSD Veterinary Manual - Aminoglycosides"},
 {category:"مضاد التهاب NSAID",name:"Meloxicam / ميلوكسيكام",aliases:["meloxicam","metacam","ميلوكسيكام"],species:all,doseMgKg:[0.05,1],route:"PO / SC",frequency:"حسب النوع والترخيص",cautions:["كلوي","renal","كبد","hepatic","جفاف","dehydrat","قرحة","ulcer","steroid","دكسا","pred"],diagnoses:["ألم","التهاب","مفاصل","أسنان"],systems:["musculoskeletal","dental","general"],source:"MSD Veterinary Manual - NSAIDs"},
 {category:"مضاد التهاب NSAID",name:"Carprofen / كاربروفين",aliases:["carprofen","rimadyl","كاربروفين"],species:["dog"],doseMgKg:[2.2,4.4],route:"PO / SC",frequency:"كل 12–24 ساعة",cautions:["كلوي","renal","كبد","hepatic","جفاف","dehydrat","قرحة","ulcer","steroid"],diagnoses:["ألم","التهاب","مفاصل","بعد عملية"],systems:["musculoskeletal","dental"],source:"MSD Veterinary Manual - NSAIDs"},
 {category:"مضاد التهاب NSAID",name:"Robenacoxib / روبيناكوكسيب",aliases:["robenacoxib","onsior","روبيناكوكسيب"],species:cd,doseMgKg:[1,2],route:"PO / SC",frequency:"كل 24 ساعة لمدة محدودة",cautions:["كلوي","renal","كبد","hepatic","جفاف","dehydrat","قرحة","ulcer","steroid"],diagnoses:["ألم","التهاب","بعد عملية"],systems:["musculoskeletal","dental"],source:"MSD Veterinary Manual - NSAIDs"},
 {category:"مضاد التهاب NSAID — تنبيه شديد",name:"Diclofenac / ديكلوفيناك (دايكلو)",aliases:["diclofenac","diclo","ديكلو","دايكلو"],species:["dog","cat"],doseMgKg:[0,0],fixedDose:"لا توجد جرعة جهازية روتينية آمنة معتمدة للكلاب أو القطط؛ لا تُحسب تلقائياً",route:"تجنّب الاستعمال الجهازي دون بروتوكول بيطري موثق",frequency:"غير معتمد روتينياً",cautions:["كلوي","renal","kidney","كبد","hepatic","جفاف","dehydrat","قرحة","ulcer","نزف","bleed","قط","cat","NSAID","steroid","دكسا","pred"],diagnoses:["ألم","التهاب"],systems:["musculoskeletal","general"],source:"MSD Veterinary Manual - NSAID and hepatotoxicity safety information"},
 {category:"كورتيزون",name:"Dexamethasone / ديكساميثازون (دكسا)",aliases:["dexamethasone","dexa","ديكساميثازون","دكسا"],species:all,doseMgKg:[0.05,0.2],route:"IV / IM / SC / PO",frequency:"حسب الاستطباب",cautions:["سكري","diabet","عدوى","infection","قرحة","ulcer","فطري","fungal","NSAID","meloxicam","carprofen","حامل","pregnan"],diagnoses:["حساسية شديدة","التهاب","صدمة","مناعي"],systems:["respiratory","integumentary","neurologic","general"],source:"MSD Veterinary Manual - Glucocorticoids"},
 {category:"كورتيزون",name:"Prednisolone / بريدنيزولون",aliases:["prednisolone","pred","بريدنيزولون","بريزلون"],species:all,doseMgKg:[0.5,2],route:"PO",frequency:"كل 12–24 ساعة ثم تخفيض تدريجي",cautions:["سكري","diabet","عدوى","infection","قرحة","ulcer","فطري","fungal","NSAID","meloxicam","carprofen","حامل","pregnan"],diagnoses:["حساسية","التهاب","مناعي","ربو"],systems:["respiratory","integumentary","digestive","general"],source:"MSD Veterinary Manual - Glucocorticoids"},
 {category:"مضاد هستامين",name:"Diphenhydramine / ديفينهيدرامين",aliases:["diphenhydramine","benadryl","ديفينهيدرامين"],species:cd,doseMgKg:[2,4],route:"PO / IM / SC",frequency:"كل 8–12 ساعة",cautions:["زرق","glaucoma","احتباس بول","urinary retention","مهدئ","sedat"],diagnoses:["حساسية","حكة","شرى"],systems:["integumentary","respiratory"],source:"MSD Veterinary Manual - Antihistamines"},
 {category:"مضاد هستامين",name:"Hydroxyzine / هيدروكسيزين",aliases:["hydroxyzine","atarax","هيدروكسيزين"],species:cd,doseMgKg:[0.5,2],route:"PO",frequency:"كل 6–12 ساعة",cautions:["كبد","hepatic","زرق","glaucoma","مهدئ","sedat"],diagnoses:["حساسية","حكة","شرى"],systems:["integumentary","respiratory"],source:"MSD Veterinary Manual - Antihistamines"},
 {category:"مضاد هستامين",name:"Cetirizine / سيتريزين",aliases:["cetirizine","zyrtec","سيتريزين"],species:cd,doseMgKg:[0.5,4],route:"PO",frequency:"كل 12–24 ساعة",cautions:["كلوي","renal","مهدئ","sedat"],diagnoses:["حساسية","حكة"],systems:["integumentary","respiratory"],source:"MSD Veterinary Manual - Second-generation antihistamines"},
 {category:"مدر بول",name:"Furosemide / فوروسيميد (لازكس)",aliases:["furosemide","lasix","فوروسيميد","فيورس امايد","لازكس"],species:all,doseMgKg:[1,4],route:"PO / IV / IM / SC",frequency:"كل 6–24 ساعة حسب الحالة والنوع",cautions:["جفاف","dehydrat","كلوي","renal","ضغط منخفض","hypot","بوتاسيوم","potassium"],diagnoses:["وذمة رئوية","فشل قلب","احتباس سوائل","استسقاء"],systems:["cardiovascular","respiratory"],source:"MSD Veterinary Manual - Diuretics"},
 {category:"مدر بول",name:"Spironolactone / سبيرونولاكتون",aliases:["spironolactone","aldactone","سبيرونولاكتون"],species:cd,doseMgKg:[1,2],route:"PO",frequency:"كل 12–24 ساعة",cautions:["كلوي","renal","بوتاسيوم","potassium","جفاف","dehydrat"],diagnoses:["فشل قلب","استسقاء"],systems:["cardiovascular"],source:"MSD Veterinary Manual - Diuretics"},
 {category:"مضاد طفيليات",name:"Fenbendazole / فينبندازول",aliases:["fenbendazole","panacur","فينبندازول"],species:all,doseMgKg:[20,50],route:"PO",frequency:"كل 24 ساعة؛ المدة حسب الطفيلي",...COMMON,diagnoses:["ديدان","جيارديا","طفيليات معوية"],systems:["digestive"]},
 {category:"مضاد طفيليات",name:"Praziquantel / برازيكوانتيل",aliases:["praziquantel","droncit","برازيكوانتيل"],species:all,doseMgKg:[5,10],route:"PO / SC / IM",frequency:"جرعة واحدة أو حسب الطفيلي",cautions:["كبد","hepatic","صغير جداً","neonate"],diagnoses:["ديدان شريطية","طفيليات"],systems:["digestive"],source:"MSD Veterinary Manual - Praziquantel"},
 {category:"مضاد طفيليات",name:"Ivermectin / إيفرمكتين",aliases:["ivermectin","ivomec","إيفرمكتين","ايفومك"],species:["dog","rabbit","bird","hamster"],doseMgKg:[0.2,0.4],route:"PO / SC",frequency:"حسب الطفيلي والنوع",cautions:["collie","MDR1","عصبي","neurolog","صغير","neonate"],diagnoses:["عث","جرب","ديدان","طفيليات"],systems:["integumentary","digestive"],source:"MSD Veterinary Manual - Macrocyclic lactones"},
 {category:"مضاد طفيليات",name:"Selamectin / سيلامكتين",aliases:["selamectin","revolution","سيلامكتين"],species:cd,doseMgKg:[6,12],route:"Topical",frequency:"شهرياً حسب المنتج",cautions:["صغير","neonate","ضعيف","debilitat"],diagnoses:["براغيث","عث الأذن","ديدان قلبية"],systems:["integumentary"],source:"MSD Veterinary Manual - Macrocyclic lactones"},
 {category:"مضاد فطري",name:"Itraconazole / إيتراكونازول",aliases:["itraconazole","sporanox","ايتراكونازول"],species:all,doseMgKg:[5,10],route:"PO",frequency:"كل 24 ساعة؛ الطيور حسب النوع",cautions:["كبد","hepatic","حامل","pregnan","قلب","cardiac","african grey"],diagnoses:["فطريات","سعفة","خمائر"],systems:["integumentary","respiratory"],source:"MSD Veterinary Manual - Antifungals"},
 {category:"مضاد فطري",name:"Fluconazole / فلوكونازول",aliases:["fluconazole","diflucan","فلوكونازول"],species:all,doseMgKg:[5,20],route:"PO / IV",frequency:"كل 12–24 ساعة",...COMMON,diagnoses:["فطريات","خمائر","كريبتوكوكوس"],systems:["integumentary","respiratory","neurologic"]},
 {category:"مضاد فطري",name:"Ketoconazole / كيتوكونازول",aliases:["ketoconazole","nizoral","كيتوكونازول"],species:["dog","bird","rabbit","hamster"],doseMgKg:[5,30],route:"PO",frequency:"كل 12–24 ساعة حسب النوع",cautions:["كبد","hepatic","حامل","pregnan","هرمونات","endocrine"],diagnoses:["فطريات","خمائر","سعفة"],systems:["integumentary"],source:"MSD Veterinary Manual - Antifungals"},
 {category:"مضاد فطري",name:"Terbinafine / تيربينافين",aliases:["terbinafine","lamisil","تيربينافين"],species:all,doseMgKg:[10,30],route:"PO",frequency:"كل 12–24 ساعة حسب النوع",...COMMON,diagnoses:["فطريات","سعفة"],systems:["integumentary"]},
 {category:"مسكن/أعصاب",name:"Gabapentin / غابابنتين",aliases:["gabapentin","neurontin","غابابنتين"],species:cd,doseMgKg:[5,20],route:"PO",frequency:"كل 8–12 ساعة",cautions:["كلوي","renal","مهدئ","sedat"],diagnoses:["ألم عصبي","ألم مزمن","قلق"],systems:["neurologic","musculoskeletal"],source:"MSD Veterinary Manual"},
 {category:"مضاد قيء",name:"Maropitant / ماروبيتانت",aliases:["maropitant","cerenia","ماروبيتانت"],species:cd,doseMgKg:[1,2],route:"SC / PO",frequency:"كل 24 ساعة",cautions:["كبد","hepatic","صغير","neonate"],diagnoses:["قيء","غثيان"],systems:["digestive"],source:"MSD Veterinary Manual - Antiemetics"},
 {category:"مضاد قيء",name:"Ondansetron / أوندانسيترون",aliases:["ondansetron","zofran","اوندانسيترون"],species:cd,doseMgKg:[0.1,0.5],route:"PO / IV",frequency:"كل 8–12 ساعة",cautions:["كبد","hepatic","قلب","QT"],diagnoses:["قيء","غثيان"],systems:["digestive"],source:"MSD Veterinary Manual - Antiemetics"},
 {category:"مضاد قيء ومحفز حركة",name:"Metoclopramide / ميتوكلوبراميد",aliases:["metoclopramide","reglan","plasil","ميتوكلوبراميد","بلاسيل"],species:cd,doseMgKg:[0.2,0.5],route:"PO / SC / IM",frequency:"كل 6–8 ساعات",cautions:["انسداد","obstruction","نزف هضمي","GI bleeding","اختلاجات","seizure","صرع","epilep"],diagnoses:["قيء","غثيان","خمول المعدة","ركودة معدية"],systems:["digestive"],source:"MSD Veterinary Manual - Prokinetic and antiemetic drugs"},
 {category:"مضاد إسهال",name:"Loperamide / لوبيراميد",aliases:["loperamide","imodium","لوبيراميد","لابروميد","لوبراميد"],species:cd,doseMgKg:[0.08,0.08],route:"PO",frequency:"كل 6–8 ساعات",cautions:["MDR1","collie","كولي","راعي أسترالي","إسهال دموي","bloody diarrhea","سموم","toxin","انسداد","obstruction","خمول","sedat"],diagnoses:["إسهال","التهاب قولون"],systems:["digestive"],source:"MSD Veterinary Manual - Antidiarrheal drugs"},
 {category:"معدة",name:"Omeprazole / أوميبرازول",aliases:["omeprazole","losec","اوميبرازول"],species:all,doseMgKg:[0.5,2],route:"PO",frequency:"كل 12–24 ساعة حسب النوع",cautions:["كبد","hepatic","استعمال طويل","long term"],diagnoses:["قرحة","ارتجاع","حموضة","التهاب معدة"],systems:["digestive"],source:"MSD Veterinary Manual - Digestive drugs"},
];
export function drugMatches(q:string,species:string){const n=q.trim().toLowerCase();if(n.length<2)return[];return VET_DRUGS.filter(d=>d.species.includes(species)&&[d.name,d.category,...d.aliases].some(x=>x.toLowerCase().includes(n))).slice(0,10)}
export function calculatedDose(d:VetDrug,w:number|null){if(d.fixedDose)return d.fixedDose;if(!w||w<=0)return`${d.doseMgKg[0]}${d.doseMgKg[1]!==d.doseMgKg[0]?`–${d.doseMgKg[1]}`:""} mg/kg`;const l=+(d.doseMgKg[0]*w).toFixed(2),h=+(d.doseMgKg[1]*w).toFixed(2);return`${l}${h!==l?`–${h}`:""} mg (${d.doseMgKg[0]}${d.doseMgKg[1]!==d.doseMgKg[0]?`–${d.doseMgKg[1]}`:""} mg/kg × ${w} kg)`}
export function drugWarnings(d:VetDrug,c:string){const n=c.toLowerCase();return d.cautions.filter(x=>n.includes(x.toLowerCase()))}
export function treatmentSuggestions(dx:string,species:string,systems:string[]=[]){const n=dx.toLowerCase();if(!n.trim()&&!systems.length)return[];return VET_DRUGS.filter(d=>d.species.includes(species)&&(d.diagnoses.some(x=>n.includes(x.toLowerCase()))||d.systems.some(x=>systems.includes(x)))).slice(0,10)}
