"use client";

import { useMemo, useState } from "react";
import { BedDouble, Loader2, Save } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { BOARDING_CAGE_NUMBERS } from "@/lib/boarding-config";
import { BREEDS, IRAQ_GOVERNORATES, SPECIES } from "@/lib/vet-data";

export type BoardingTarget = { cageNumber?: number; patient?: { patientId: string; petName: string; species: string } };
type Draft = { cageNumber: string; stayType: "medical" | "hotel"; checkInDate: string; numberOfDays: string; dailyRateIqd: string; paidIqd: string; medicalSigns: string; diagnosis: string; treatmentPlan: string; careInstructions: string; notes: string; ownerName: string; phone: string; governorate: string; area: string; petName: string; species: string; breed: string; sex: string; ageValue: string; ageUnit: string; color: string };
const today = () => new Date().toISOString().slice(0, 10);
function blank(target: BoardingTarget): Draft { const species = target.patient?.species || "cat"; return { cageNumber: String(target.cageNumber ?? 1), stayType: target.patient ? "medical" : "hotel", checkInDate: today(), numberOfDays: "1", dailyRateIqd: "", paidIqd: "", medicalSigns: "", diagnosis: "", treatmentPlan: "", careInstructions: "", notes: "", ownerName: "", phone: "", governorate: "بغداد", area: "", petName: target.patient?.petName || "", species, breed: BREEDS[species]?.[0] ?? "", sex: "غير محدد", ageValue: "", ageUnit: "سنة", color: "" }; }
const dateAfter = (start: string, days: number) => { const value = new Date(`${start}T12:00:00`); value.setDate(value.getDate() + Math.max(1, days)); return value.toISOString().slice(0, 10); };

export function BoardingSheet({ target, onOpenChange, onSaved }: { target: BoardingTarget | null; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  return <Sheet open={Boolean(target)} onOpenChange={onOpenChange}><SheetContent side="left" className="w-full overflow-y-auto p-0 sm:max-w-3xl">{target && <BoardingForm key={`${target.patient?.patientId ?? "new"}-${target.cageNumber ?? "any"}`} target={target} onCancel={() => onOpenChange(false)} onSaved={onSaved} />}</SheetContent></Sheet>;
}

function BoardingForm({ target, onCancel, onSaved }: { target: BoardingTarget; onCancel: () => void; onSaved: () => void }) {
  const [draft, setDraft] = useState(() => blank(target)); const [saving, setSaving] = useState(false); const breeds = useMemo(() => BREEDS[draft.species] ?? [], [draft.species]);
  const set = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const total = (Number(draft.numberOfDays) || 0) * (Number(draft.dailyRateIqd) || 0); const remaining = Math.max(0, total - (Number(draft.paidIqd) || 0));
  async function save() {
    if (!target.patient && (!draft.ownerName.trim() || !draft.phone.trim() || !draft.petName.trim())) return toast.error("أكمل اسم المربي ورقمه واسم الحيوان.");
    setSaving(true);
    try {
      const response = await fetch("/api/clinic/boarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cageNumber: Number(draft.cageNumber), stayType: draft.stayType, patientId: target.patient?.patientId ?? null, profile: target.patient ? null : { owner: { name: draft.ownerName, phone: draft.phone, email: "", governorate: draft.governorate, area: draft.area }, patient: { name: draft.petName, species: draft.species, breed: draft.breed, sex: draft.sex, ageValue: draft.ageValue ? Number(draft.ageValue) : null, ageUnit: draft.ageUnit, birthDate: null, color: draft.color, weightKg: null, microchip: "", reproductiveStatus: "غير محدد", drugAllergies: "لا توجد حساسية معروفة", sensitivityNotes: "" } }, checkInDate: draft.checkInDate, expectedCheckoutDate: dateAfter(draft.checkInDate, Number(draft.numberOfDays) || 1), numberOfDays: Number(draft.numberOfDays), dailyRateIqd: Number(draft.dailyRateIqd) || 0, totalIqd: total, paidIqd: Number(draft.paidIqd) || 0, medicalSigns: draft.medicalSigns, diagnosis: draft.diagnosis, treatmentPlan: draft.treatmentPlan, careInstructions: draft.careInstructions, notes: draft.notes }) });
      const result = (await response.json()) as { error?: string; message?: string }; if (!response.ok) throw new Error(result.error || "تعذّر تسجيل المبيت."); toast.success(result.message); onSaved(); onCancel();
    } catch (error) { toast.error(error instanceof Error ? error.message : "تعذّر تسجيل المبيت."); } finally { setSaving(false); }
  }
  return <div className="flex min-h-full flex-col"><SheetHeader className="sticky top-0 z-10 border-b bg-white/95 px-6 py-5 backdrop-blur"><SheetTitle className="flex items-center gap-2"><BedDouble className="size-5 text-[#2563eb]" />تسجيل مبيت جديد</SheetTitle><SheetDescription>{target.patient ? `إضافة ${target.patient.petName} إلى المبيت من ملفه المسجل.` : "فندقة جديدة مع تسجيل المربي والحيوان."}</SheetDescription></SheetHeader><div className="flex-1 space-y-7 p-6">
    <div className="grid gap-4 sm:grid-cols-2"><Field label="رقم القفص"><Select value={draft.cageNumber} onValueChange={(value) => set("cageNumber", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{BOARDING_CAGE_NUMBERS.map((number) => <SelectItem key={number} value={String(number)}>القفص {number}</SelectItem>)}</SelectContent></Select></Field><Field label="نوع المبيت"><Select value={draft.stayType} onValueChange={(value) => set("stayType", value as "medical" | "hotel")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="medical">مبيت مرضي</SelectItem><SelectItem value="hotel">فندقة</SelectItem></SelectContent></Select></Field></div>
    {!target.patient && <><h3 className="border-b pb-3 font-black text-[#2563eb]">بيانات المربي والحيوان</h3><div className="grid gap-4 sm:grid-cols-2"><Field label="اسم المربي"><Input value={draft.ownerName} onChange={(event) => set("ownerName", event.target.value)} /></Field><Field label="رقم الهاتف"><Input dir="ltr" className="text-right" value={draft.phone} onChange={(event) => set("phone", event.target.value)} /></Field><Field label="المحافظة"><Select value={draft.governorate} onValueChange={(value) => set("governorate", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{IRAQ_GOVERNORATES.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field><Field label="العنوان / المنطقة"><Input value={draft.area} onChange={(event) => set("area", event.target.value)} /></Field><Field label="اسم الحيوان"><Input value={draft.petName} onChange={(event) => set("petName", event.target.value)} /></Field><Field label="الفصيلة"><Select value={draft.species} onValueChange={(value) => { set("species", value); set("breed", BREEDS[value]?.[0] ?? ""); }}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{SPECIES.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></Field><Field label="السلالة"><Select value={draft.breed} onValueChange={(value) => set("breed", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{breeds.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field><Field label="الجنس"><Select value={draft.sex} onValueChange={(value) => set("sex", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ذكر">ذكر</SelectItem><SelectItem value="أنثى">أنثى</SelectItem><SelectItem value="غير محدد">غير محدد</SelectItem></SelectContent></Select></Field><Field label="العمر"><div className="grid grid-cols-[1fr_100px] gap-2"><Input type="number" min="0" value={draft.ageValue} onChange={(event) => set("ageValue", event.target.value)} /><Select value={draft.ageUnit} onValueChange={(value) => set("ageUnit", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="شهر">شهر</SelectItem><SelectItem value="سنة">سنة</SelectItem></SelectContent></Select></div></Field><Field label="اللون"><Input value={draft.color} onChange={(event) => set("color", event.target.value)} /></Field></div></>}
    <h3 className="border-b pb-3 font-black text-[#2563eb]">المدة والحساب</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="تاريخ الدخول"><Input type="date" value={draft.checkInDate} onChange={(event) => set("checkInDate", event.target.value)} /></Field><Field label="عدد الأيام"><Input type="number" min="1" value={draft.numberOfDays} onChange={(event) => set("numberOfDays", event.target.value)} /></Field><Field label="سعر اليوم"><Input type="number" min="0" value={draft.dailyRateIqd} onChange={(event) => set("dailyRateIqd", event.target.value)} /></Field><Field label="المبلغ المدفوع"><Input type="number" min="0" value={draft.paidIqd} onChange={(event) => set("paidIqd", event.target.value)} /></Field></div><div className="grid gap-3 rounded-2xl bg-[#eef2ff] p-4 sm:grid-cols-3"><Summary label="الإجمالي" value={total} /><Summary label="المدفوع" value={Number(draft.paidIqd) || 0} /><Summary label="المتبقي" value={remaining} /></div>
    {draft.stayType === "medical" && <><h3 className="border-b pb-3 font-black text-[#2563eb]">تفاصيل المبيت المرضي</h3><div className="grid gap-4"><Field label="العلامات والحالة عند الدخول"><Textarea value={draft.medicalSigns} onChange={(event) => set("medicalSigns", event.target.value)} rows={3} /></Field><Field label="التشخيص"><Textarea value={draft.diagnosis} onChange={(event) => set("diagnosis", event.target.value)} rows={3} /></Field><Field label="العلاج والخطة"><Textarea value={draft.treatmentPlan} onChange={(event) => set("treatmentPlan", event.target.value)} rows={3} /></Field></div></>}
    <Field label="تعليمات الرعاية / الغذاء / الأدوية"><Textarea value={draft.careInstructions} onChange={(event) => set("careInstructions", event.target.value)} rows={3} /></Field><Field label="ملاحظات إضافية"><Textarea value={draft.notes} onChange={(event) => set("notes", event.target.value)} rows={3} /></Field>
  </div><SheetFooter className="sticky bottom-0 border-t bg-white/95 px-6 py-4 backdrop-blur sm:flex-row sm:justify-between"><Button type="button" variant="outline" onClick={onCancel}>إلغاء</Button><Button type="button" className="bg-[#2563eb]" disabled={saving} onClick={save}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}حفظ المبيت</Button></SheetFooter></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Summary({ label, value }: { label: string; value: number }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-black text-[#2563eb]">{value.toLocaleString("ar-IQ")} د.ع</p></div>; }
